##basics
exec-once=~/.config/hypr/xdg-portals.sh
exec-once = hyprpm reload -n #plugin reload
exec-once = waybar #top bar
exec-once = udiskie -t #drive control
#clip
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
#polkit
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swaync
exec-once = waypaper --restore & waypaper --random
##autorun useful programs
windowrulev2 = workspace 1 silent, title:^(Zen Browser)$
windowrulev2 = workspace 5 silent, class:^(equibop)$
windowrulev2 = workspace 5 silent, class:^(ayugram-desktop)$

exec-once = [workspace 1] zen-browser
exec-once = [workspace 2] kitty
